// Golden-file tests for the tools.gen.ts emitter (scripts/emitter.ts).
// The committed fixture at test/golden/tools.gen.txt locks the exact output;
// the diagnostics check proves the emission type-checks against src/client.ts.

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ModuleKind, ModuleResolutionKind, Project, ScriptTarget } from 'ts-morph';
import { docsUrlFor, emitToolsModule, hasDocsPage, type ToolDefinition } from '../scripts/emitter.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const GOLDEN_PATH = join(HERE, 'golden', 'tools.gen.txt');
const HEADER = '// This file is auto-generated by scripts/generate.ts. Do not edit.';

// Deliberately includes: enum + optional members, an empty schema, a name that
// sanitizes identically to another tool (collision), a missing description,
// and tools declaring an outputSchema (typed results) including a Result-name collision.
const FIXTURE_TOOLS: ToolDefinition[] = [
  {
    name: 'web_search',
    description: 'Search the web.',
    inputSchema: {
      type: 'object',
      properties: { query: { type: 'string' }, time_range: { type: 'string' } },
      required: ['query'],
      additionalProperties: false,
    },
  },
  {
    name: 'connect_telegram',
    description: 'Links Telegram.',
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
  },
  {
    name: 'generate_video',
    description: 'Generates video.',
    inputSchema: {
      type: 'object',
      properties: {
        orientation: { type: 'string', enum: ['landscape', 'portrait'] },
        tags: { type: 'array', items: { type: 'string' } },
      },
      required: ['orientation'],
      additionalProperties: false,
    },
  },
  {
    name: 'web__search',
    inputSchema: { type: 'object', properties: { q: { type: 'string' } }, required: ['q'], additionalProperties: false },
  },
  {
    name: 'sum_two_numbers',
    description: 'Adds two integers.',
    inputSchema: {
      type: 'object',
      properties: { a: { type: 'integer' }, b: { type: 'integer' } },
      required: ['a', 'b'],
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: { sum: { type: 'integer' } },
      required: ['sum'],
      additionalProperties: false,
    },
  },
  {
    name: 'sum__two_numbers',
    description: 'Adds two integers (duplicate name collision).',
    inputSchema: {
      type: 'object',
      properties: { x: { type: 'integer' }, y: { type: 'integer' } },
      required: ['x', 'y'],
      additionalProperties: false,
    },
    outputSchema: {
      type: 'object',
      properties: { total: { type: 'integer' } },
      required: ['total'],
      additionalProperties: false,
    },
  },
];

function flattenDiagnostic(message: unknown): string {
  if (typeof message === 'string') return message;
  const obj = message as { _compilerObject?: unknown; messageText?: unknown; next?: unknown };
  const target = (obj?._compilerObject ?? obj) as { messageText?: unknown; next?: unknown };
  const text = typeof target?.messageText === 'string' ? target.messageText : flattenDiagnostic(target?.messageText);
  const next = Array.isArray(target?.next)
    ? ' — ' + target.next.map((n) => flattenDiagnostic(n)).join(' — ')
    : '';
  return text + next;
}

describe('docsUrlFor', () => {
  // Slugs verified against https://docs.zocomputer.com/llms.txt (tools/ pages).
  it('maps tool names to kebab-case docs pages', () => {
    assert.equal(docsUrlFor('bash'), 'https://docs.zocomputer.com/tools/bash.md');
    assert.equal(docsUrlFor('edit_file_llm'), 'https://docs.zocomputer.com/tools/edit-file-llm.md');
    assert.equal(docsUrlFor('grep_search'), 'https://docs.zocomputer.com/tools/grep-search.md');
    assert.equal(docsUrlFor('set_active_persona'), 'https://docs.zocomputer.com/tools/set-active-persona.md');
    assert.equal(
      docsUrlFor('use_app_google_calendar'),
      'https://docs.zocomputer.com/tools/use-app-google-calendar.md',
    );
  });
});

describe('emitToolsModule', () => {
  it('matches the committed golden file byte-for-byte', async () => {
    const out = await emitToolsModule(FIXTURE_TOOLS, HEADER);
    const golden = await readFile(GOLDEN_PATH, 'utf8');
    assert.equal(out, golden);
  });

  it('is deterministic across runs', async () => {
    assert.equal(
      await emitToolsModule(FIXTURE_TOOLS, HEADER),
      await emitToolsModule([...FIXTURE_TOOLS].reverse(), HEADER),
    );
  });

  it('emits code that type-checks against src/client.ts', async () => {
    const out = await emitToolsModule(FIXTURE_TOOLS, HEADER);
    const project = new Project({
      compilerOptions: {
        strict: true,
        target: ScriptTarget.ES2022,
        module: ModuleKind.NodeNext,
        moduleResolution: ModuleResolutionKind.NodeNext,
      },
    });
    project.createSourceFile('src/client.ts', await readFile(join(HERE, '..', 'src', 'client.ts'), 'utf8'), {
      overwrite: true,
    });
    project.createSourceFile('src/tools.gen.ts', out, { overwrite: true });
    const messages = project
      .getPreEmitDiagnostics()
      .map((diag) => flattenDiagnostic(diag.getMessageText()));
    assert.deepEqual(messages, []);
  });

  it('dedupes colliding method names with deterministic suffixes', async () => {
    const out = await emitToolsModule(FIXTURE_TOOLS, HEADER);
    assert.match(out, /webSearch\(args: WebSearchArgs\)/);
    assert.match(out, /callTool\("web__search", args\)/);
    assert.match(out, /webSearch_2\(args: WebSearch2Args\)/);
    assert.match(out, /callTool\("web_search", args\)/);
  });

  it('types results for tools declaring an outputSchema', async () => {
    const out = await emitToolsModule(FIXTURE_TOOLS, HEADER);
    assert.match(out, /export interface SumTwoNumbersResult \{[\s\S]*?sum: number;/);
    assert.match(
      out,
      /sumTwoNumbers\(args: SumTwoNumbersArgs\): Promise<McpToolResult<SumTwoNumbersResult>>/,
    );
    // Schemaless tools stay unparameterized.
    assert.match(out, /webSearch_2\(args: WebSearch2Args\): Promise<McpToolResult>/);
  });

  it('suffixes colliding Result interface names deterministically', async () => {
    const out = await emitToolsModule(FIXTURE_TOOLS, HEADER);
    assert.match(out, /interface SumTwoNumbersResult \{/);
    assert.match(out, /interface SumTwoNumbers2Result \{/);
    assert.match(out, /Promise<McpToolResult<SumTwoNumbers2Result>>/);
  });

  it('exposes a runtime TOOL_NAMES registry', async () => {
    const out = await emitToolsModule(FIXTURE_TOOLS, HEADER);
    const match = out.match(/export const TOOL_NAMES = (\[[^\]]+\]) as const;/);
    assert.ok(match, 'TOOL_NAMES declaration missing');
    assert.deepEqual(JSON.parse(match[1].replaceAll("'", '"')), [
      'connect_telegram',
      'generate_video',
      'sum__two_numbers',
      'sum_two_numbers',
      'web__search',
      'web_search',
    ]);
  });

  it('treats boolean outputSchemas as absent (not valid MCP schemas)', async () => {
    const out = await emitToolsModule(
      [
        {
          name: 'bool_schema_tool',
          inputSchema: { type: 'object', properties: {}, additionalProperties: false },
          outputSchema: false as never,
        },
      ],
      HEADER,
    );
    assert.doesNotMatch(out, /export interface \w+Result/);
    assert.match(out, /boolSchemaTool\(args: BoolSchemaToolArgs\): Promise<McpToolResult>/);
  });

  it('links every method to its official docs page', async () => {
    const out = await emitToolsModule(FIXTURE_TOOLS, HEADER);
    assert.match(
      out,
      /\* Search the web\.\r?\n\s+\* Docs: https:\/\/docs\.zocomputer\.com\/tools\/web-search\.md/,
    );
    // Description-less tools still get the link as their whole doc.
    assert.match(out, /Docs: https:\/\/docs\.zocomputer\.com\/tools\/sum-two-numbers\.md/);
    assert.match(out, /Docs: https:\/\/docs\.zocomputer\.com\/tools\/connect-telegram\.md/);
  });

  it('suppresses the Docs line for tools with no docs page', async () => {
    assert.equal(hasDocsPage('bash'), true);
    assert.equal(hasDocsPage('create_agent'), false);
    assert.equal(hasDocsPage('tool_docs'), false);

    const out = await emitToolsModule(
      [
        {
          name: 'create_agent',
          description: 'Undocumented upstream.',
          inputSchema: { type: 'object', properties: {}, additionalProperties: false },
        },
      ],
      HEADER,
    );
    // Description kept; no dead link emitted.
    assert.match(out, /\/\*\* Undocumented upstream\. \*\//);
    assert.doesNotMatch(out, /docs\.zocomputer\.com/);
  });

  it('handles an empty tool inventory', async () => {
    const out = await emitToolsModule([], HEADER);
    assert.match(out, /export class ZoComputerClient extends McpClientBase/);
    assert.match(out, /export const TOOL_NAMES = \[\] as const;/);
    assert.doesNotMatch(out, /callTool/);
  });
});
