// Golden-file tests for the tools.gen.ts emitter (scripts/emitter.ts).
// The committed fixture at test/golden/tools.gen.txt locks the exact output;
// the diagnostics check proves the emission type-checks against src/client.ts.

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ModuleKind, ModuleResolutionKind, Project, ScriptTarget } from 'ts-morph';
import { emitToolsModule, type ToolDefinition } from '../scripts/emitter.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const GOLDEN_PATH = join(HERE, 'golden', 'tools.gen.txt');
const HEADER = '// This file is auto-generated by scripts/generate.ts. Do not edit.';

// Deliberately includes: enum + optional members, an empty schema, a name that
// sanitizes identically to another tool (collision), and a missing description.
const FIXTURE_TOOLS: ToolDefinition[] = [
  {
    name: 'web_search',
    description: 'Search the web.',
    inputSchema: {
      type: 'object',
      properties: { query: { type: 'string' }, time_range: { type: 'string' } },
      required: ['query'],
      additionalProperties: false,
    },
  },
  {
    name: 'connect_telegram',
    description: 'Links Telegram.',
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
  },
  {
    name: 'generate_video',
    description: 'Generates video.',
    inputSchema: {
      type: 'object',
      properties: {
        orientation: { type: 'string', enum: ['landscape', 'portrait'] },
        tags: { type: 'array', items: { type: 'string' } },
      },
      required: ['orientation'],
      additionalProperties: false,
    },
  },
  {
    name: 'web__search',
    inputSchema: { type: 'object', properties: { q: { type: 'string' } }, required: ['q'], additionalProperties: false },
  },
];

function flattenDiagnostic(message: unknown): string {
  if (typeof message === 'string') return message;
  const obj = message as { _compilerObject?: unknown; messageText?: unknown; next?: unknown };
  const target = (obj?._compilerObject ?? obj) as { messageText?: unknown; next?: unknown };
  const text = typeof target?.messageText === 'string' ? target.messageText : flattenDiagnostic(target?.messageText);
  const next = Array.isArray(target?.next)
    ? ' — ' + target.next.map((n) => flattenDiagnostic(n)).join(' — ')
    : '';
  return text + next;
}

describe('emitToolsModule', () => {
  it('matches the committed golden file byte-for-byte', async () => {
    const out = await emitToolsModule(FIXTURE_TOOLS, HEADER);
    const golden = await readFile(GOLDEN_PATH, 'utf8');
    assert.equal(out, golden);
  });

  it('is deterministic across runs', async () => {
    assert.equal(
      await emitToolsModule(FIXTURE_TOOLS, HEADER),
      await emitToolsModule([...FIXTURE_TOOLS].reverse(), HEADER),
    );
  });

  it('emits code that type-checks against src/client.ts', async () => {
    const out = await emitToolsModule(FIXTURE_TOOLS, HEADER);
    const project = new Project({
      compilerOptions: {
        strict: true,
        target: ScriptTarget.ES2022,
        module: ModuleKind.NodeNext,
        moduleResolution: ModuleResolutionKind.NodeNext,
      },
    });
    project.createSourceFile('src/client.ts', await readFile(join(HERE, '..', 'src', 'client.ts'), 'utf8'), {
      overwrite: true,
    });
    project.createSourceFile('src/tools.gen.ts', out, { overwrite: true });
    const messages = project
      .getPreEmitDiagnostics()
      .map((diag) => flattenDiagnostic(diag.getMessageText()));
    assert.deepEqual(messages, []);
  });

  it('dedupes colliding method names with deterministic suffixes', async () => {
    const out = await emitToolsModule(FIXTURE_TOOLS, HEADER);
    assert.match(out, /webSearch\(args: WebSearchArgs\)/);
    assert.match(out, /callTool\("web__search", args\)/);
    assert.match(out, /webSearch_2\(args: WebSearch2Args\)/);
    assert.match(out, /callTool\("web_search", args\)/);
  });

  it('exposes a runtime TOOL_NAMES registry', async () => {
    const out = await emitToolsModule(FIXTURE_TOOLS, HEADER);
    const match = out.match(/export const TOOL_NAMES = (\[[^\]]+\]) as const;/);
    assert.ok(match, 'TOOL_NAMES declaration missing');
    assert.deepEqual(JSON.parse(match[1].replaceAll("'", '"')), [
      'connect_telegram',
      'generate_video',
      'web__search',
      'web_search',
    ]);
  });

  it('handles an empty tool inventory', async () => {
    const out = await emitToolsModule([], HEADER);
    assert.match(out, /export class ZoComputerClient extends McpClientBase/);
    assert.match(out, /export const TOOL_NAMES = \[\] as const;/);
    assert.doesNotMatch(out, /callTool/);
  });
});
