// Regenerates src/tools.gen.ts from Zo Computer's live MCP endpoint.
//
//   ZO_API_KEY=... npm run sync:mcp
//
// Fetches tools/list from https://api.zo.computer/mcp (or ZO_MCP_URL), writes
// a raw snapshot to openapi/mcp-tools.json and the typed client to
// src/tools.gen.ts. Without credentials the script falls back to the
// checked-in snapshot so `npm run check` stays green in CI.

import { readFile, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { McpClientBase, DEFAULT_BASE_URL } from '@/client.js';
import { emitToolsModule, type ToolDefinition } from './emitter.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const SNAPSHOT_PATH = join(ROOT, 'openapi', 'mcp-tools.json');
const OUTPUT_PATH = join(ROOT, 'src', 'tools.gen.ts');

const BASE_URL = process.env.ZO_MCP_URL ?? DEFAULT_BASE_URL;
const TOKEN = process.env.ZO_API_KEY ?? process.env.ZO_CLIENT_IDENTITY_TOKEN ?? '';

const HEADER = [
  '// This file is auto-generated by scripts/generate.ts from',
  "// openapi/mcp-tools.json (fetched from Zo Computer's MCP endpoint). Do not edit by hand.",
  '',
].join('\n');

async function fetchLiveTools(): Promise<ToolDefinition[]> {
  const mcp = new McpClientBase({ baseUrl: BASE_URL, auth: TOKEN || undefined });
  await mcp.connect();
  try {
    return (await mcp.listTools()) as ToolDefinition[];
  } finally {
    await mcp.close();
  }
}

async function readSnapshotTools(): Promise<ToolDefinition[]> {
  const raw = JSON.parse(await readFile(SNAPSHOT_PATH, 'utf8')) as { tools?: ToolDefinition[] };
  if (!Array.isArray(raw.tools) || raw.tools.length === 0) {
    throw new Error('snapshot has no tools');
  }
  return raw.tools;
}

let tools: ToolDefinition[];
try {
  if (!TOKEN) throw new Error('no ZO_API_KEY / ZO_CLIENT_IDENTITY_TOKEN set');
  console.log(`Fetching tools/list from ${BASE_URL}...`);
  tools = await fetchLiveTools();
  await writeFile(SNAPSHOT_PATH, JSON.stringify({ tools }, null, 2) + '\n', 'utf8');
  console.log(`Fetched ${tools.length} tools; snapshot updated.`);
} catch (err) {
  const reason = err instanceof Error ? err.message : String(err);
  if (!TOKEN) {
    console.warn(`No token; MCP sync skipped (${reason}). Using checked-in snapshot.`);
  } else {
    console.error(`MCP tools/list failed (${reason}). Falling back to checked-in snapshot.`);
  }
  tools = await readSnapshotTools();
  console.log(`Loaded ${tools.length} tools from snapshot.`);
}

await writeFile(OUTPUT_PATH, await emitToolsModule(tools, HEADER), 'utf8');
console.log(`Wrote ${OUTPUT_PATH}`);
